### ISSUE TITLE
Skip step "prepare" of plugin "@google/semantic-release-replace-plugin" in dry-run mode

### ISSUE THREAD

**Issue by xmnlab** [jpoehnelt/semantic-release-replace-plugin#169]
hi everyone!
is there a way to test the match in dry-run mode? thanks

**Comment by Daniele-Tentoni** [comment]
I would like to test it too

**Comment by xmnlab** [comment]
just a friendly reminder about this issue

**Comment by jpoehnelt** [comment]
Looks like it isn't possible to do.

> The objective of the dry-run mode is to get a preview of the pending release. Dry-run mode skips the following steps: **prepare**, publish, addChannel, success and fail. In addition to this it prints the next version and release notes to the console.

https://semantic-release.gitbook.io/semantic-release/usage/configuration#dryrun

**Comment by xmnlab** [comment]
got it .. thanks for the explanation @jpoehnelt !
