### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by xmnlab** [jpoehnelt/semantic-release-replace-plugin#221]
Hi everyone!

running semantic-release in dry-run mode is raising the following error:

```
[11:29:37 PM] [semantic-release] › ℹ  Running semantic-release version 21.0.7
[11:29:37 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/xmn/.npm/_npx/1bba8fa66517c824/node_modules/lodash-es/lodash.js from /home/xmn/.npm/_npx/1bba8fa66517c824/node_modules/semantic-release-replace-plugin/dist/index.js not supported.
Instead change the require of lodash.js in /home/xmn/.npm/_npx/1bba8fa66517c824/node_modules/semantic-release-replace-plugin/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/xmn/.npm/_npx/1bba8fa66517c824/node_modules/semantic-release-replace-plugin/dist/index.js:70:19) {
  code: 'ERR_REQUIRE_ESM'
}
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/xmn/.npm/_npx/1bba8fa66517c824/node_modules/lodash-es/lodash.js from /home/xmn/.npm/_npx/1bba8fa66517c824/node_modules/semantic-release-replace-plugin/dist/index.js not supported.
Instead change the require of lodash.js in /home/xmn/.npm/_npx/1bba8fa66517c824/node_modules/semantic-release-replace-plugin/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/xmn/.npm/_npx/1bba8fa66517c824/node_modules/semantic-release-replace-plugin/dist/index.js:70:19) {
  code: 'ERR_REQUIRE_ESM'
} 
```

I am not super familiar with nodejs ... any idea about what is happening?
thanks!

**Comment by GruenSein** [comment]
I have the same issue ever since v1.2.x releases. At first, I thought it was my configuration since the plugin had been renamed but even after fixing all these issues the problem persists rendering my previously working release workflow completely unusable. Any help would be appreciated.

**Comment by KennyLindahl** [comment]
**It should be possible to downgrade to** `@google/semantic-release-replace-plugin@1.2.0`, and it should work.

I also encountered this issue and compared it with the last successful deploy and it was `1.2.0` is when it worked, the latest version right now (`1.2.1`) is causing the issue described in the OP.

<hr/>

I think there is a fix for this on the way here: https://github.com/jpoehnelt/semantic-release-replace-plugin/pull/222
@jpoehnelt When can we expect this to be merged and published to NPM?
By the way, please make sure to not release it as a major release so it will automatically be resolved for most people.

Thanks

**Comment by jpoehnelt** [comment]
Please try semantic-release-replace-plugin@1.2.4.

**Comment by rv-gbell** [comment]
@jpoehnelt I am not seeing OP's issue resolved as of the latest (1.2.6) release.  Am I missing something?

**Comment by DanielMcAssey** [comment]
Same here, same issue

**Comment by jpoehnelt** [comment]
Please try https://www.npmjs.com/package/semantic-release-replace-plugin/v/1.2.7 which includes changes from https://github.com/jpoehnelt/semantic-release-replace-plugin/commit/90c29769dfe709821f9aa475c23068ac42d6182e.

**Comment by KennyLindahl** [comment]
@jpoehnelt Thanks.

<hr />

Just to highlight, this version requires:
- Node 18 or above
- Peer dependency to `semantic-release` version `20.1.0` or above

If anyone want to resolve the issue and not want to change the dependencies, then i suggest to install the earlier working version (`1.2.0`):
- Put this in your `package.json`: `@google/semantic-release-replace-plugin@1.2.0`

**Comment by jpoehnelt** [comment]
> Just to highlight, this version requires:
> 
> * Node 18 or above
> * Peer dependency to `semantic-release` version `20.1.0` or above

@KennyLindahl Please note that these are the same settings used by many of the most popular semantic release plugins at this time.

See https://github.com/semantic-release/semantic-release/issues/2133
![Screenshot 2023-07-20 at 10 57 15 AM](https://github.com/jpoehnelt/semantic-release-replace-plugin/assets/3392975/f9de14db-6c58-4903-858a-3d01d255c920)

**Comment by jpoehnelt** [comment]
Closing this as there have been no reports. Please comment if you have an issue with `>1.2.7`. Sorry for the maintenance burden, the CJS/ESM churn is not fun 🤮 .

**Comment by xmnlab** [comment]
thanks for all the work on this lib @jpoehnelt !
it is a great tool!
